# Generated by Django 4.1 on 2024-11-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='img_content',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
