# Generated by Django 5.1.2 on 2024-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document_img_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
